/**
 * Plain-text summary builders for the floating calculator's Copy / Save-to-
 * Case actions — ported from TC-app FloatingCalc.tsx, re-signed for the
 * platform (never "DentaFlow").
 *
 * SIGNATURE (PM ruling 6.3): this text goes to patients, so it is signed with
 * the practice name from config when we have one (`/auth/me` →
 * tenant.displayName), falling back to "CareIN TC" when the tenant isn't
 * resolved. We never sign with a vendor name the patient has never heard of if
 * the practice's own name is available.
 *
 * DOLLARS DOMAIN: formats scratchpad dollars via calcFinance's formatters.
 */

import { amortize, fmtUSD, fmtUSD0, type FinanceResult } from "./calcFinance";
import type { COBInput, COBResult } from "../lib/calcCOB";

export type CalcMode = "simple" | "full" | "cob";

export const DEFAULT_COPY_SIGNER = "CareIN TC";

function signature(practiceName?: string | null): string {
  const signer = practiceName?.trim() || DEFAULT_COPY_SIGNER;
  return `Generated by ${signer} · ${new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`;
}

export interface CopyTextArgs {
  mode: Exclude<CalcMode, "cob">;
  treatmentName: string;
  fee: number;
  showInsurance: boolean;
  insuranceEst: number;
  downPayAmt: number;
  financedWithFee: number;
  applyServiceFee: boolean;
  serviceFeeAmt: number;
  serviceFeePercent: number;
  apr: number;
  simpleTerm: number;
  lanes: { label: string; result: FinanceResult }[];
  /** Practice name for the signature; falls back to DEFAULT_COPY_SIGNER. */
  practiceName?: string | null;
}

export function buildCopyText({
  mode, treatmentName, fee, showInsurance, insuranceEst, downPayAmt,
  financedWithFee, applyServiceFee, serviceFeeAmt, serviceFeePercent,
  apr, simpleTerm, lanes, practiceName,
}: CopyTextArgs): string {
  const parts: string[] = [];

  parts.push(`Treatment Plan — ${treatmentName || "Untitled"}`);

  const meta: string[] = [`Fee: ${fmtUSD0(fee)}`];
  if (showInsurance && insuranceEst > 0) meta.push(`Insurance: -${fmtUSD0(insuranceEst)}`);
  if (downPayAmt > 0) meta.push(`Down: -${fmtUSD0(downPayAmt)}`);
  parts.push(meta.join("  |  "));

  let financedLine = `Amount to Finance: ${fmtUSD0(financedWithFee)}`;
  if (applyServiceFee && serviceFeeAmt > 0) {
    financedLine += ` (includes +${fmtUSD0(serviceFeeAmt)} ${serviceFeePercent}% service fee)`;
  }
  parts.push(financedLine);
  parts.push("");

  if (mode === "simple") {
    const { monthly, total, interest } = amortize(financedWithFee, apr, simpleTerm);
    const aprLabel = apr === 0 ? "0% APR" : `${apr.toFixed(2)}% APR`;
    parts.push(`Monthly Payment @ ${simpleTerm}mo, ${aprLabel}: ${fmtUSD(monthly)}`);
    parts.push(`Total: ${fmtUSD0(total)}`);
    if (apr > 0) parts.push(`Interest: ${fmtUSD0(interest)}`);
  } else {
    for (const lane of lanes) {
      const r = lane.result;
      if (!r.eligible) continue;
      const aprLabel = r.apr === 0 ? "0% APR" : `${r.apr}% APR`;
      parts.push(`--- ${lane.label} (${r.months}mo, ${aprLabel}) ---`);
      parts.push(`Monthly: ${fmtUSD(r.monthly)}  |  Total: ${fmtUSD0(r.totalIfOnTime)}`);
      if (r.merchantFee > 0) {
        parts.push(`Merchant fee: ${fmtUSD0(r.merchantFee)}  |  Net to practice: ${fmtUSD0(r.netToPractice)}`);
      }
      if (r.warning) parts.push(`Note: ${r.warning}`);
      parts.push("");
    }
  }

  parts.push(signature(practiceName));
  return parts.join("\n");
}

export function buildCobCopyText(
  input: COBInput,
  result: COBResult,
  practiceName?: string | null,
): string {
  const parts: string[] = [];
  parts.push("Coordination of Benefits — patient out-of-pocket estimate");
  parts.push(`Method: ${result.methodLabel}`);
  parts.push("");

  parts.push("Primary plan:");
  parts.push(
    `  Allowed: ${fmtUSD0(input.primary.allowedAmount)} · Coverage: ${input.primary.coveragePct}% · Ded remaining: ${fmtUSD0(input.primary.remainingDeductible)} · ${input.primary.hasAnnualMax ? `Max remaining: ${fmtUSD0(input.primary.remainingAnnualMax)}` : "Max: unlimited"} · ${input.primary.inNetwork ? "In-network" : "Out-of-network"}`,
  );
  parts.push("Secondary plan:");
  parts.push(
    `  Allowed: ${fmtUSD0(input.secondary.allowedAmount)} · Coverage: ${input.secondary.coveragePct}% · Ded remaining: ${fmtUSD0(input.secondary.remainingDeductible)} · ${input.secondary.hasAnnualMax ? `Max remaining: ${fmtUSD0(input.secondary.remainingAnnualMax)}` : "Max: unlimited"} · ${input.secondary.inNetwork ? "In-network" : "Out-of-network"}`,
  );
  if (input.secondaryWaivesDeductible) parts.push("  (secondary waives its deductible)");
  parts.push("");

  if (result.lines.length > 1) {
    parts.push("Line items:");
    for (const l of result.lines) {
      parts.push(
        `  ${l.label} — fee ${fmtUSD(l.contractedFee)} · primary ${fmtUSD(l.primaryPaid)} · secondary ${fmtUSD(l.secondaryPaid)} · write-off ${fmtUSD(l.writeOff)} · patient ${fmtUSD(l.patientPortion)}`,
      );
    }
    parts.push("");
  }

  parts.push(`Primary paid:        ${fmtUSD(result.totalPrimaryPaid)}`);
  parts.push(`Secondary paid:      ${fmtUSD(result.totalSecondaryPaid)}`);
  parts.push(`Total insurance:     ${fmtUSD(result.totalInsurancePaid)}`);
  parts.push(`Write-off:           ${fmtUSD(result.totalWriteOff)}`);
  parts.push(`Patient out-of-pocket: ${fmtUSD(result.totalPatientPortion)}`);
  parts.push("");
  parts.push(signature(practiceName));
  return parts.join("\n");
}
