// CareIn Mock Data — realistic dental practice AI call center data

export const mockLiveCalls = [
  {
    id: "call_live_001",
    source: "retell" as const,
    agentId: "agent_rover_main",
    agentName: "Rover",
    fromNumber: "+1 (602) 555-0142",
    patientName: "Sarah Mitchell",
    duration: 127,
    status: "active" as const,
    intent: "Appointment Scheduling",
    sentiment: "positive" as const,
    transcript: [
      { role: "agent", text: "Thank you for calling Downtown Dental, this is Rover. How can I help you today?", ts: 0 },
      { role: "patient", text: "Hi, I need to schedule a cleaning for next week if possible.", ts: 4 },
      { role: "agent", text: "I'd be happy to help you with that! Let me check our availability for next week.", ts: 8 },
      { role: "patient", text: "I prefer mornings, maybe Tuesday or Wednesday?", ts: 14 },
      { role: "agent", text: "We have Tuesday at 9:00 AM and Wednesday at 10:30 AM available. Which works better for you?", ts: 18 },
    ],
    startTime: new Date(Date.now() - 127000).toISOString(),
  },
  {
    id: "call_live_002",
    source: "retell" as const,
    agentId: "agent_rover_main",
    agentName: "Rover",
    fromNumber: "+1 (602) 555-0287",
    patientName: "James Kowalski",
    duration: 43,
    status: "active" as const,
    intent: "Emergency / Pain",
    sentiment: "negative" as const,
    isEmergency: true,
    transcript: [
      { role: "agent", text: "Thank you for calling Downtown Dental, this is Rover. How can I help you today?", ts: 0 },
      { role: "patient", text: "I'm having really bad tooth pain, it started last night and I can't sleep.", ts: 4 },
      { role: "agent", text: "I'm so sorry to hear that. This sounds like it may need urgent attention. Let me connect you with our team right away.", ts: 9 },
    ],
    startTime: new Date(Date.now() - 43000).toISOString(),
  },
  {
    id: "call_live_003",
    source: "mango" as const,
    agentName: "Staff",
    fromNumber: "+1 (480) 555-0391",
    patientName: "Unknown",
    duration: 215,
    status: "active" as const,
    intent: "Insurance Inquiry",
    sentiment: "neutral" as const,
    startTime: new Date(Date.now() - 215000).toISOString(),
  },
];

export const mockCalls = [
  {
    id: "call_001",
    source: "retell" as const,
    agentName: "Rover",
    fromNumber: "+1 (602) 555-0142",
    patientName: "Sarah Mitchell",
    patientId: "pat_001",
    duration: 187,
    status: "completed" as const,
    intent: "Appointment Scheduling",
    sentiment: "positive" as const,
    outcome: "Booked",
    date: new Date(Date.now() - 3600000).toISOString(),
    hasRecording: true,
    hasTranscript: true,
    summary: "Patient scheduled a cleaning for Tuesday 9 AM. Confirmed insurance on file.",
  },
  {
    id: "call_002",
    source: "retell" as const,
    agentName: "Rover",
    fromNumber: "+1 (480) 555-0287",
    patientName: "James Kowalski",
    patientId: "pat_002",
    duration: 95,
    status: "transferred" as const,
    intent: "Emergency / Pain",
    sentiment: "negative" as const,
    outcome: "Transferred",
    date: new Date(Date.now() - 7200000).toISOString(),
    hasRecording: true,
    hasTranscript: true,
    summary: "Patient reported severe tooth pain. Transferred to front desk for emergency slot.",
    isEmergency: true,
  },
  {
    id: "call_003",
    source: "mango" as const,
    agentName: "Staff",
    fromNumber: "+1 (623) 555-0156",
    patientName: "Maria Gonzalez",
    patientId: "pat_003",
    duration: 312,
    status: "completed" as const,
    intent: "Insurance Verification",
    sentiment: "neutral" as const,
    outcome: "Resolved",
    date: new Date(Date.now() - 10800000).toISOString(),
    hasRecording: true,
    hasTranscript: false,
  },
  {
    id: "call_004",
    source: "retell" as const,
    agentName: "Rover",
    fromNumber: "+1 (602) 555-0391",
    patientName: "David Chen",
    patientId: "pat_004",
    duration: 143,
    status: "completed" as const,
    intent: "Appointment Reschedule",
    sentiment: "positive" as const,
    outcome: "Rescheduled",
    date: new Date(Date.now() - 14400000).toISOString(),
    hasRecording: true,
    hasTranscript: true,
    summary: "Patient rescheduled from Monday to Thursday 2 PM due to work conflict.",
  },
  {
    id: "call_005",
    source: "retell" as const,
    agentName: "Rover",
    fromNumber: "+1 (480) 555-0512",
    patientName: "New Patient",
    duration: 228,
    status: "completed" as const,
    intent: "New Patient Inquiry",
    sentiment: "positive" as const,
    outcome: "Booked",
    date: new Date(Date.now() - 18000000).toISOString(),
    hasRecording: true,
    hasTranscript: true,
    summary: "New patient inquiry. Collected demographics, scheduled initial exam for next Friday.",
  },
  {
    id: "call_006",
    source: "retell" as const,
    agentName: "Rover",
    fromNumber: "+1 (602) 555-0634",
    patientName: "Linda Thompson",
    patientId: "pat_006",
    duration: 67,
    status: "voicemail" as const,
    intent: "General Inquiry",
    sentiment: "neutral" as const,
    outcome: "Voicemail",
    date: new Date(Date.now() - 21600000).toISOString(),
    hasRecording: false,
    hasTranscript: true,
  },
  {
    id: "call_007",
    source: "mango" as const,
    agentName: "Staff",
    fromNumber: "+1 (623) 555-0748",
    patientName: "Robert Kim",
    patientId: "pat_007",
    duration: 445,
    status: "completed" as const,
    intent: "Treatment Plan Discussion",
    sentiment: "neutral" as const,
    outcome: "Follow-up Needed",
    date: new Date(Date.now() - 25200000).toISOString(),
    hasRecording: true,
    hasTranscript: false,
  },
];

export const mockAgents = [
  {
    id: "agent_rover_main",
    name: "Rover",
    description: "Primary inbound dental front desk AI agent. Handles scheduling, new patients, general inquiries, and emergency triage.",
    voice: "Aria",
    voiceProvider: "elevenlabs",
    language: "en-US",
    status: "active" as const,
    phoneNumbers: ["+1 (602) 555-0100", "+1 (602) 555-0101"],
    callsToday: 24,
    callsTotal: 1847,
    avgDuration: 178,
    successRate: 87,
    model: "gpt-4o",
    prompt: `You are Rover, the friendly and professional AI receptionist for {{office_name}}. 

Your primary responsibilities:
1. Greet callers warmly and identify their needs
2. Schedule, reschedule, or cancel appointments
3. Answer general questions about services and hours
4. Collect new patient information
5. Triage dental emergencies and transfer when needed
6. Verify insurance information

Always be empathetic, especially with patients in pain. For emergencies, prioritize getting them seen same-day.

Office hours: Monday-Friday 8 AM - 5 PM, Saturday 9 AM - 2 PM.`,
    tools: ["check_availability", "book_appointment", "cancel_appointment", "collect_patient_info", "transfer_call"],
    createdAt: "2024-01-15",
    lastModified: "2025-02-28",
  },
  {
    id: "agent_recall_01",
    name: "Recall Assistant",
    description: "Handles recall reminders and appointment confirmations for patients due for cleanings.",
    voice: "Sophia",
    voiceProvider: "elevenlabs",
    language: "en-US",
    status: "inactive" as const,
    phoneNumbers: [],
    callsToday: 0,
    callsTotal: 342,
    avgDuration: 95,
    successRate: 72,
    model: "gpt-4o-mini",
    prompt: "You are a recall reminder assistant...",
    tools: ["check_patient_recall", "book_appointment", "send_confirmation"],
    createdAt: "2024-06-01",
    lastModified: "2025-01-10",
  },
];

export const mockCallbacks = [
  {
    id: "cb_001",
    patientName: "Marcus Williams",
    phone: "+1 (602) 555-0891",
    reason: "Insurance pre-auth needed before scheduling crown",
    priority: "high" as const,
    status: "pending" as const,
    dueDate: new Date(Date.now() + 3600000).toISOString(),
    assignedTo: "Front Desk",
    attempts: 1,
    lastAttempt: new Date(Date.now() - 7200000).toISOString(),
    notes: "Called once, no answer. Try again before 3 PM.",
    linkedCallId: "call_008",
  },
  {
    id: "cb_002",
    patientName: "Jennifer Park",
    phone: "+1 (480) 555-0234",
    reason: "Patient requested callback about treatment plan cost",
    priority: "medium" as const,
    status: "pending" as const,
    dueDate: new Date(Date.now() + 7200000).toISOString(),
    assignedTo: "Treatment Coordinator",
    attempts: 0,
    notes: "New patient, first visit was yesterday.",
  },
  {
    id: "cb_003",
    patientName: "Tom Bradley",
    phone: "+1 (623) 555-0567",
    reason: "Post-extraction follow-up",
    priority: "high" as const,
    status: "in-progress" as const,
    dueDate: new Date(Date.now() + 1800000).toISOString(),
    assignedTo: "Clinical Team",
    attempts: 2,
    lastAttempt: new Date(Date.now() - 3600000).toISOString(),
    notes: "Patient had extraction yesterday. Check for complications.",
    linkedCallId: "call_009",
  },
  {
    id: "cb_004",
    patientName: "Angela Foster",
    phone: "+1 (602) 555-0123",
    reason: "Appointment confirmation — no response to automated reminder",
    priority: "low" as const,
    status: "pending" as const,
    dueDate: new Date(Date.now() + 86400000).toISOString(),
    assignedTo: "Front Desk",
    attempts: 0,
  },
  {
    id: "cb_005",
    patientName: "Carlos Rivera",
    phone: "+1 (480) 555-0789",
    reason: "Billing question about EOB",
    priority: "medium" as const,
    status: "completed" as const,
    dueDate: new Date(Date.now() - 3600000).toISOString(),
    assignedTo: "Billing",
    attempts: 1,
    completedAt: new Date(Date.now() - 1800000).toISOString(),
    notes: "Resolved — explained insurance payment timeline.",
  },
];

export const mockAppointments = [
  { id: "apt_001", patientName: "Sarah Mitchell", time: "09:00", duration: 60, type: "Cleaning", provider: "Dr. Johnson", operatory: "Op 1", status: "confirmed" as const },
  { id: "apt_002", patientName: "David Chen", time: "09:30", duration: 90, type: "Crown Prep", provider: "Dr. Smith", operatory: "Op 2", status: "confirmed" as const },
  { id: "apt_003", patientName: "Maria Gonzalez", time: "10:00", duration: 45, type: "X-Ray + Exam", provider: "Dr. Johnson", operatory: "Op 3", status: "confirmed" as const },
  { id: "apt_004", patientName: "New Patient", time: "10:30", duration: 60, type: "New Patient Exam", provider: "Dr. Smith", operatory: "Op 1", status: "unconfirmed" as const },
  { id: "apt_005", patientName: "Linda Thompson", time: "11:00", duration: 30, type: "Filling", provider: "Dr. Lee", operatory: "Op 2", status: "confirmed" as const },
  { id: "apt_006", patientName: "Robert Kim", time: "13:00", duration: 120, type: "Root Canal", provider: "Dr. Smith", operatory: "Op 3", status: "confirmed" as const },
  { id: "apt_007", patientName: "Angela Foster", time: "14:00", duration: 60, type: "Cleaning", provider: "Dr. Johnson", operatory: "Op 1", status: "unconfirmed" as const },
  { id: "apt_008", patientName: "Marcus Williams", time: "15:00", duration: 90, type: "Crown Delivery", provider: "Dr. Smith", operatory: "Op 2", status: "confirmed" as const },
];

export const mockAnalyticsData = {
  callVolume: [
    { date: "Mon", retell: 28, mango: 12 },
    { date: "Tue", retell: 35, mango: 15 },
    { date: "Wed", retell: 31, mango: 18 },
    { date: "Thu", retell: 42, mango: 14 },
    { date: "Fri", retell: 38, mango: 20 },
    { date: "Sat", retell: 22, mango: 8 },
    { date: "Sun", retell: 5, mango: 2 },
  ],
  intentBreakdown: [
    { name: "Scheduling", value: 42 },
    { name: "Reschedule/Cancel", value: 18 },
    { name: "New Patient", value: 15 },
    { name: "Emergency", value: 8 },
    { name: "Insurance", value: 10 },
    { name: "General", value: 7 },
  ],
  sentimentTrend: [
    { date: "Mon", positive: 68, neutral: 22, negative: 10 },
    { date: "Tue", positive: 72, neutral: 20, negative: 8 },
    { date: "Wed", positive: 65, neutral: 25, negative: 10 },
    { date: "Thu", positive: 75, neutral: 18, negative: 7 },
    { date: "Fri", positive: 70, neutral: 22, negative: 8 },
    { date: "Sat", positive: 78, neutral: 16, negative: 6 },
  ],
  hourlyVolume: [
    { hour: "8AM", calls: 8 },
    { hour: "9AM", calls: 22 },
    { hour: "10AM", calls: 31 },
    { hour: "11AM", calls: 28 },
    { hour: "12PM", calls: 15 },
    { hour: "1PM", calls: 19 },
    { hour: "2PM", calls: 24 },
    { hour: "3PM", calls: 27 },
    { hour: "4PM", calls: 18 },
    { hour: "5PM", calls: 9 },
  ],
};

export function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

export function formatTimeAgo(isoString: string): string {
  const diff = Date.now() - new Date(isoString).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}
