/**
 * Copy-text builders: CareIN signature (not DentaFlow), simple-mode math line,
 * ineligible-lane skipping, and COB summary content.
 */
import { describe, expect, it } from "vitest";
import {
  buildCobCopyText,
  buildCopyText,
  DEFAULT_COPY_SIGNER,
} from "../client/src/features/tc/calc/copyText";
import { inHousePlan, cherry } from "../client/src/features/tc/calc/calcFinance";
import { calcCOB, type COBInput } from "../client/src/features/tc/lib/calcCOB";

const baseArgs = {
  treatmentName: "Crown",
  fee: 1300,
  showInsurance: true,
  insuranceEst: 500,
  downPayAmt: 100,
  financedWithFee: 700,
  applyServiceFee: false,
  serviceFeeAmt: 0,
  serviceFeePercent: 0,
  apr: 0,
  simpleTerm: 12,
  lanes: [] as { label: string; result: ReturnType<typeof inHousePlan> }[],
};

describe("buildCopyText", () => {
  it("falls back to the CareIN TC signature, never DentaFlow", () => {
    const text = buildCopyText({ ...baseArgs, mode: "simple" });
    expect(text).toContain(`Generated by ${DEFAULT_COPY_SIGNER} ·`);
    expect(text).not.toContain("DentaFlow");
  });

  it("prefers the practice name when config gives us one", () => {
    const text = buildCopyText({
      ...baseArgs,
      mode: "simple",
      practiceName: "Valley Family Dental",
    });
    expect(text).toContain("Generated by Valley Family Dental ·");
    expect(text).not.toContain(DEFAULT_COPY_SIGNER);
  });

  it("ignores a blank/whitespace practice name", () => {
    for (const name of [null, undefined, "", "   "]) {
      const text = buildCopyText({ ...baseArgs, mode: "simple", practiceName: name });
      expect(text).toContain(`Generated by ${DEFAULT_COPY_SIGNER} ·`);
    }
  });

  it("simple mode reports the 0% monthly as an even split", () => {
    const text = buildCopyText({ ...baseArgs, mode: "simple" });
    expect(text).toContain("Monthly Payment @ 12mo, 0% APR: $58.33");
    expect(text).toContain("Insurance: -$500");
    expect(text).toContain("Down: -$100");
    expect(text).toContain("Amount to Finance: $700");
  });

  it("full mode lists eligible lanes and skips ineligible ones", () => {
    const eligible = inHousePlan(700, 12);
    const ineligible = cherry(150, 3); // below Cherry's $200 minimum
    expect(ineligible.eligible).toBe(false);
    const text = buildCopyText({
      ...baseArgs,
      mode: "full",
      lanes: [
        { label: "In-house Plan", result: eligible },
        { label: "Cherry", result: ineligible },
      ],
    });
    expect(text).toContain("--- In-house Plan (12mo, 0% APR) ---");
    expect(text).not.toContain("--- Cherry");
  });
});

describe("buildCobCopyText", () => {
  it("summarizes both plans, the method, and totals with the fallback signature", () => {
    const input: COBInput = {
      method: "full-cob",
      secondaryWaivesDeductible: false,
      primary: {
        allowedAmount: 1000,
        coveragePct: 50,
        remainingDeductible: 0,
        hasAnnualMax: false,
        remainingAnnualMax: 0,
        inNetwork: true,
      },
      secondary: {
        allowedAmount: 1100,
        coveragePct: 60,
        remainingDeductible: 50,
        hasAnnualMax: false,
        remainingAnnualMax: 0,
        inNetwork: false,
      },
      dentistFee: 1300,
    };
    const result = calcCOB(input);
    const text = buildCobCopyText(input, result);
    expect(text).toContain("Coordination of Benefits — patient out-of-pocket estimate");
    expect(text).toContain(`Method: ${result.methodLabel}`);
    expect(text).toContain("Primary plan:");
    expect(text).toContain("Secondary plan:");
    expect(text).toContain("Patient out-of-pocket:");
    expect(text).toContain(`Generated by ${DEFAULT_COPY_SIGNER} ·`);
    expect(text).not.toContain("DentaFlow");

    // Same practice-name preference as the financing copy.
    const signed = buildCobCopyText(input, result, "Roland Family Dental");
    expect(signed).toContain("Generated by Roland Family Dental ·");
    expect(signed).not.toContain(DEFAULT_COPY_SIGNER);
  });
});
