/**
 * Seed / fixture data for the CareIN AI Call Dashboard.
 *
 * IMPORTANT: All names, numbers, and details are synthetic and fictional.
 * No PHI is included. Uses realistic but entirely made-up data.
 */

import type { Call } from "./types.js";

/** Generates an ISO timestamp offset by `offsetMs` from now. */
function ago(offsetMs: number): string {
  return new Date(Date.now() - offsetMs).toISOString();
}

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

export const SEED_CALLS: Call[] = [
  // -------------------------------------------------------------------------
  // Downtown Dental — +16025550101
  // -------------------------------------------------------------------------
  {
    id: "call_seed_001",
    startedAt: ago(1 * HOUR),
    endedAt: ago(1 * HOUR - 3 * 60 * 1000),
    durationSeconds: 180,
    callerNumber: "+16025550142",
    callerName: "Sarah Mitchell",
    office: "Downtown Dental",
    toNumber: "+16025550101",
    tag: "appointment_scheduled",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Downtown Dental, this is Rover. How can I help?\nPatient: Hi, I'd like to schedule a cleaning.\nAgent: Of course! We have Tuesday at 9 AM or Wednesday at 10:30 AM.\nPatient: Tuesday works great.\nAgent: Perfect, I've booked you for Tuesday at 9 AM. Is there anything else?",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Downtown Dental, this is Rover. How can I help?" },
      { role: "user", content: "Hi, I'd like to schedule a cleaning." },
      { role: "agent", content: "Of course! We have Tuesday at 9 AM or Wednesday at 10:30 AM." },
      { role: "user", content: "Tuesday works great." },
      { role: "agent", content: "Perfect, I've booked you for Tuesday at 9 AM. Is there anything else?" },
    ],
    summary: "Patient Sarah Mitchell called to schedule a routine cleaning. Appointment booked for Tuesday at 9:00 AM.",
    outcome: "Appointment scheduled",
    sentiment: "positive",
    qualityScore: 92,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "written",
    commlogWrittenAt: ago(55 * 60 * 1000),
    commlogError: null,
    retellCallId: "retell_001",
    ingestedAt: ago(1 * HOUR),
  },
  {
    id: "call_seed_002",
    startedAt: ago(2 * HOUR),
    endedAt: ago(2 * HOUR - 45 * 1000),
    durationSeconds: 45,
    callerNumber: "+16025550287",
    callerName: "James Kowalski",
    office: "Downtown Dental",
    toNumber: "+16025550101",
    tag: "emergency",
    routedTo: "Front Desk Staff",
    transcript: "Agent: Thank you for calling Downtown Dental, this is Rover. How can I help?\nPatient: I have severe tooth pain, started last night.\nAgent: I'm sorry to hear that. Let me connect you with our team right away.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Downtown Dental, this is Rover. How can I help?" },
      { role: "user", content: "I have severe tooth pain, started last night." },
      { role: "agent", content: "I'm sorry to hear that. Let me connect you with our team right away." },
    ],
    summary: "Emergency call. Patient James Kowalski reported severe tooth pain. Escalated immediately to front desk staff.",
    outcome: "Escalated to staff",
    sentiment: "negative",
    qualityScore: 61,
    recordingUrl: "",
    isEmergency: true,
    commlogStatus: "written",
    commlogWrittenAt: ago(115 * 60 * 1000),
    commlogError: null,
    retellCallId: "retell_002",
    ingestedAt: ago(2 * HOUR),
  },
  {
    id: "call_seed_003",
    startedAt: ago(3 * HOUR),
    endedAt: ago(3 * HOUR - 120 * 1000),
    durationSeconds: 120,
    callerNumber: "+16025550391",
    callerName: "Maria Gonzalez",
    office: "Downtown Dental",
    toNumber: "+16025550101",
    tag: "billing_inquiry",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Downtown Dental.\nPatient: Hi, I have a question about my last bill.\nAgent: I can help with that. Can you share the invoice date?\nPatient: It was from March 15th.\nAgent: Got it. Your balance is $125 for the exam and X-rays.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Downtown Dental." },
      { role: "user", content: "Hi, I have a question about my last bill." },
      { role: "agent", content: "I can help with that. Can you share the invoice date?" },
      { role: "user", content: "It was from March 15th." },
      { role: "agent", content: "Got it. Your balance is $125 for the exam and X-rays." },
    ],
    summary: "Patient Maria Gonzalez called with a billing inquiry about a March 15 invoice. Balance of $125 confirmed.",
    outcome: "Billing inquiry handled",
    sentiment: "neutral",
    qualityScore: 72,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "written",
    commlogWrittenAt: ago(175 * 60 * 1000),
    commlogError: null,
    retellCallId: "retell_003",
    ingestedAt: ago(3 * HOUR),
  },
  // -------------------------------------------------------------------------
  // Scottsdale North — +14805550202
  // -------------------------------------------------------------------------
  {
    id: "call_seed_004",
    startedAt: ago(4 * HOUR),
    endedAt: ago(4 * HOUR - 90 * 1000),
    durationSeconds: 90,
    callerNumber: "+14805550411",
    callerName: "Robert Chen",
    office: "Scottsdale North",
    toNumber: "+14805550202",
    tag: "appointment_cancelled",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Scottsdale North Dental.\nPatient: I need to cancel my appointment Thursday.\nAgent: I can do that for you. Your Thursday 2 PM appointment has been cancelled.\nPatient: Thank you.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Scottsdale North Dental." },
      { role: "user", content: "I need to cancel my appointment Thursday." },
      { role: "agent", content: "I can do that for you. Your Thursday 2 PM appointment has been cancelled." },
      { role: "user", content: "Thank you." },
    ],
    summary: "Patient Robert Chen cancelled his Thursday 2 PM appointment. No rebooking.",
    outcome: "Appointment cancelled",
    sentiment: "neutral",
    qualityScore: 68,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "written",
    commlogWrittenAt: ago(235 * 60 * 1000),
    commlogError: null,
    retellCallId: "retell_004",
    ingestedAt: ago(4 * HOUR),
  },
  {
    id: "call_seed_005",
    startedAt: ago(5 * HOUR),
    endedAt: ago(5 * HOUR - 200 * 1000),
    durationSeconds: 200,
    callerNumber: "+14805550512",
    callerName: "Emily Watson",
    office: "Scottsdale North",
    toNumber: "+14805550202",
    tag: "new_patient_inquiry",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Scottsdale North Dental.\nPatient: Hi, I'm looking for a new dentist. Do you accept new patients?\nAgent: We do! We'd love to have you. Let me get some information and schedule your first visit.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Scottsdale North Dental." },
      { role: "user", content: "Hi, I'm looking for a new dentist. Do you accept new patients?" },
      { role: "agent", content: "We do! We'd love to have you. Let me get some information and schedule your first visit." },
    ],
    summary: "New patient Emily Watson inquired about becoming a patient at Scottsdale North. New patient appointment scheduled for next Monday.",
    outcome: "New patient inquiry handled",
    sentiment: "positive",
    qualityScore: 88,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "pending",
    commlogWrittenAt: null,
    commlogError: null,
    retellCallId: "retell_005",
    ingestedAt: ago(5 * HOUR),
  },
  {
    id: "call_seed_006",
    startedAt: ago(6 * HOUR),
    endedAt: ago(6 * HOUR - 30 * 1000),
    durationSeconds: 30,
    callerNumber: "+14805550613",
    callerName: "Unknown",
    office: "Scottsdale North",
    toNumber: "+14805550202",
    tag: "voicemail",
    routedTo: "Voicemail",
    transcript: "Agent: Thank you for calling Scottsdale North Dental. We're unavailable right now. Please leave a message.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Scottsdale North Dental. We're unavailable right now. Please leave a message." },
    ],
    summary: "Caller reached voicemail outside business hours. No message left.",
    outcome: "Voicemail left",
    sentiment: "neutral",
    qualityScore: 50,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "pending",
    commlogWrittenAt: null,
    commlogError: null,
    retellCallId: "retell_006",
    ingestedAt: ago(6 * HOUR),
  },
  // -------------------------------------------------------------------------
  // Mesa East — +14805550303
  // -------------------------------------------------------------------------
  {
    id: "call_seed_007",
    startedAt: ago(1 * DAY + 1 * HOUR),
    endedAt: ago(1 * DAY + 1 * HOUR - 150 * 1000),
    durationSeconds: 150,
    callerNumber: "+14805550714",
    callerName: "Linda Park",
    office: "Mesa East",
    toNumber: "+14805550303",
    tag: "appointment_rescheduled",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Mesa East Dental.\nPatient: I need to reschedule my appointment from Friday to next week.\nAgent: No problem. We have Monday at 11 AM or Wednesday at 3 PM.\nPatient: Wednesday at 3 works.\nAgent: Great, I've moved your appointment to Wednesday at 3 PM.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Mesa East Dental." },
      { role: "user", content: "I need to reschedule my appointment from Friday to next week." },
      { role: "agent", content: "No problem. We have Monday at 11 AM or Wednesday at 3 PM." },
      { role: "user", content: "Wednesday at 3 works." },
      { role: "agent", content: "Great, I've moved your appointment to Wednesday at 3 PM." },
    ],
    summary: "Patient Linda Park rescheduled her Friday appointment to Wednesday at 3 PM.",
    outcome: "Appointment rescheduled",
    sentiment: "positive",
    qualityScore: 85,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "written",
    commlogWrittenAt: ago(1 * DAY + 55 * 60 * 1000),
    commlogError: null,
    retellCallId: "retell_007",
    ingestedAt: ago(1 * DAY + 1 * HOUR),
  },
  {
    id: "call_seed_008",
    startedAt: ago(1 * DAY + 2 * HOUR),
    endedAt: ago(1 * DAY + 2 * HOUR - 75 * 1000),
    durationSeconds: 75,
    callerNumber: "+14805550815",
    callerName: "David Torres",
    office: "Mesa East",
    toNumber: "+14805550303",
    tag: "insurance_inquiry",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Mesa East Dental.\nPatient: Do you accept Delta Dental insurance?\nAgent: Yes, we are in-network with Delta Dental. Would you like to schedule an appointment?",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Mesa East Dental." },
      { role: "user", content: "Do you accept Delta Dental insurance?" },
      { role: "agent", content: "Yes, we are in-network with Delta Dental. Would you like to schedule an appointment?" },
    ],
    summary: "Patient David Torres inquired about Delta Dental insurance acceptance. Confirmed in-network status.",
    outcome: "Insurance inquiry handled",
    sentiment: "positive",
    qualityScore: 76,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "failed",
    commlogWrittenAt: null,
    commlogError: "Open Dental API timeout after 30s",
    retellCallId: "retell_008",
    ingestedAt: ago(1 * DAY + 2 * HOUR),
  },
  {
    id: "call_seed_009",
    startedAt: ago(2 * DAY + 3 * HOUR),
    endedAt: ago(2 * DAY + 3 * HOUR - 60 * 1000),
    durationSeconds: 60,
    callerNumber: "+16235550916",
    callerName: "Patricia Kim",
    office: "Surprise West",
    toNumber: "+16235550404",
    tag: "completed",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Surprise West Dental.\nPatient: I just wanted to confirm my appointment tomorrow at 10.\nAgent: Confirmed! We'll see you tomorrow at 10 AM.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Surprise West Dental." },
      { role: "user", content: "I just wanted to confirm my appointment tomorrow at 10." },
      { role: "agent", content: "Confirmed! We'll see you tomorrow at 10 AM." },
    ],
    summary: "Patient Patricia Kim confirmed her appointment for tomorrow at 10 AM.",
    outcome: "Call completed",
    sentiment: "positive",
    qualityScore: 80,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "written",
    commlogWrittenAt: ago(2 * DAY + 175 * 60 * 1000),
    commlogError: null,
    retellCallId: "retell_009",
    ingestedAt: ago(2 * DAY + 3 * HOUR),
  },
  {
    id: "call_seed_010",
    startedAt: ago(2 * DAY + 5 * HOUR),
    endedAt: ago(2 * DAY + 5 * HOUR - 240 * 1000),
    durationSeconds: 240,
    callerNumber: "+16235550917",
    callerName: "Michael Adams",
    office: "Surprise West",
    toNumber: "+16235550404",
    tag: "appointment_scheduled",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Surprise West Dental.\nPatient: My name is Michael Adams. I need a crown consultation.\nAgent: Of course, Dr. Johnson has availability next Thursday at 2 PM.\nPatient: That works for me.\nAgent: Perfect. I've scheduled you for Thursday at 2 PM with Dr. Johnson.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Surprise West Dental." },
      { role: "user", content: "My name is Michael Adams. I need a crown consultation." },
      { role: "agent", content: "Of course, Dr. Johnson has availability next Thursday at 2 PM." },
      { role: "user", content: "That works for me." },
      { role: "agent", content: "Perfect. I've scheduled you for Thursday at 2 PM with Dr. Johnson." },
    ],
    summary: "Patient Michael Adams scheduled a crown consultation for Thursday at 2 PM with Dr. Johnson.",
    outcome: "Appointment scheduled",
    sentiment: "positive",
    qualityScore: 90,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "written",
    commlogWrittenAt: ago(2 * DAY + 295 * 60 * 1000),
    commlogError: null,
    retellCallId: "retell_010",
    ingestedAt: ago(2 * DAY + 5 * HOUR),
  },
  {
    id: "call_seed_011",
    startedAt: ago(3 * DAY + 1 * HOUR),
    endedAt: ago(3 * DAY + 1 * HOUR - 180 * 1000),
    durationSeconds: 180,
    callerNumber: "+16025550143",
    callerName: "Angela Rivera",
    office: "Downtown Dental",
    toNumber: "+16025550101",
    tag: "transferred",
    routedTo: "Front Desk Staff",
    transcript: "Agent: Thank you for calling Downtown Dental.\nPatient: I need to speak with someone about my treatment plan.\nAgent: I'll connect you with our patient coordinator right away.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Downtown Dental." },
      { role: "user", content: "I need to speak with someone about my treatment plan." },
      { role: "agent", content: "I'll connect you with our patient coordinator right away." },
    ],
    summary: "Patient Angela Rivera requested to speak with the patient coordinator about her treatment plan. Call transferred to front desk.",
    outcome: "Transferred to staff",
    sentiment: "neutral",
    qualityScore: 65,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "pending",
    commlogWrittenAt: null,
    commlogError: null,
    retellCallId: "retell_011",
    ingestedAt: ago(3 * DAY + 1 * HOUR),
  },
  {
    id: "call_seed_012",
    startedAt: ago(3 * DAY + 4 * HOUR),
    endedAt: ago(3 * DAY + 4 * HOUR - 110 * 1000),
    durationSeconds: 110,
    callerNumber: "+14805550516",
    callerName: "Unknown",
    office: "Scottsdale North",
    toNumber: "+14805550202",
    tag: "unresolved",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Scottsdale North Dental.\nPatient: I want to change my appointment but I don't know the date.\nAgent: I can help if you can confirm your name or phone number on file.\nPatient: Hmm, I'm not sure. Let me check and call back.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Scottsdale North Dental." },
      { role: "user", content: "I want to change my appointment but I don't know the date." },
      { role: "agent", content: "I can help if you can confirm your name or phone number on file." },
      { role: "user", content: "Hmm, I'm not sure. Let me check and call back." },
    ],
    summary: "Caller attempted to reschedule but could not confirm identity. Call ended without resolution.",
    outcome: "Unresolved",
    sentiment: "neutral",
    qualityScore: 42,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "pending",
    commlogWrittenAt: null,
    commlogError: null,
    retellCallId: "retell_012",
    ingestedAt: ago(3 * DAY + 4 * HOUR),
  },
  {
    id: "call_seed_013",
    startedAt: ago(5 * DAY + 2 * HOUR),
    endedAt: ago(5 * DAY + 2 * HOUR - 95 * 1000),
    durationSeconds: 95,
    callerNumber: "+14805550818",
    callerName: "Jennifer Lee",
    office: "Mesa East",
    toNumber: "+14805550303",
    tag: "appointment_scheduled",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Mesa East Dental.\nPatient: My name is Jennifer Lee. I need a teeth cleaning next week.\nAgent: We have openings next Tuesday at 2 PM or Friday at 9 AM.\nPatient: Friday at 9 AM please.\nAgent: Booked! See you Friday at 9 AM.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Mesa East Dental." },
      { role: "user", content: "My name is Jennifer Lee. I need a teeth cleaning next week." },
      { role: "agent", content: "We have openings next Tuesday at 2 PM or Friday at 9 AM." },
      { role: "user", content: "Friday at 9 AM please." },
      { role: "agent", content: "Booked! See you Friday at 9 AM." },
    ],
    summary: "Patient Jennifer Lee scheduled a cleaning appointment for Friday at 9 AM.",
    outcome: "Appointment scheduled",
    sentiment: "positive",
    qualityScore: 91,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "written",
    commlogWrittenAt: ago(5 * DAY + 115 * 60 * 1000),
    commlogError: null,
    retellCallId: "retell_013",
    ingestedAt: ago(5 * DAY + 2 * HOUR),
  },
  {
    id: "call_seed_014",
    startedAt: ago(7 * DAY + 3 * HOUR),
    endedAt: ago(7 * DAY + 3 * HOUR - 300 * 1000),
    durationSeconds: 300,
    callerNumber: "+16235550919",
    callerName: "Thomas Wright",
    office: "Surprise West",
    toNumber: "+16235550404",
    tag: "billing_inquiry",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Surprise West Dental.\nPatient: I got a bill and I don't understand the charges.\nAgent: I'd be happy to help. Can you tell me the date of service?\nPatient: It says April 3rd.\nAgent: For April 3rd, you had a filling and X-rays, totaling $320 after insurance.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Surprise West Dental." },
      { role: "user", content: "I got a bill and I don't understand the charges." },
      { role: "agent", content: "I'd be happy to help. Can you tell me the date of service?" },
      { role: "user", content: "It says April 3rd." },
      { role: "agent", content: "For April 3rd, you had a filling and X-rays, totaling $320 after insurance." },
    ],
    summary: "Patient Thomas Wright inquired about an April 3rd bill for $320 covering a filling and X-rays.",
    outcome: "Billing inquiry handled",
    sentiment: "neutral",
    qualityScore: 73,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "failed",
    commlogWrittenAt: null,
    commlogError: "Open Dental connection refused",
    retellCallId: "retell_014",
    ingestedAt: ago(7 * DAY + 3 * HOUR),
  },
  {
    id: "call_seed_015",
    startedAt: ago(8 * DAY + 1 * HOUR),
    endedAt: ago(8 * DAY + 1 * HOUR - 130 * 1000),
    durationSeconds: 130,
    callerNumber: "+16025550144",
    callerName: "Nancy Brown",
    office: "Downtown Dental",
    toNumber: "+16025550101",
    tag: "appointment_scheduled",
    routedTo: "Rover (AI)",
    transcript: "Agent: Thank you for calling Downtown Dental.\nPatient: My name is Nancy Brown. I need to schedule my 6-month checkup.\nAgent: Of course! We have next Monday at 10 AM available.\nPatient: Perfect.\nAgent: Booked for Monday at 10 AM.",
    transcriptObject: [
      { role: "agent", content: "Thank you for calling Downtown Dental." },
      { role: "user", content: "My name is Nancy Brown. I need to schedule my 6-month checkup." },
      { role: "agent", content: "Of course! We have next Monday at 10 AM available." },
      { role: "user", content: "Perfect." },
      { role: "agent", content: "Booked for Monday at 10 AM." },
    ],
    summary: "Patient Nancy Brown scheduled her 6-month checkup for Monday at 10 AM.",
    outcome: "Appointment scheduled",
    sentiment: "positive",
    qualityScore: 88,
    recordingUrl: "",
    isEmergency: false,
    commlogStatus: "written",
    commlogWrittenAt: ago(8 * DAY + 55 * 60 * 1000),
    commlogError: null,
    retellCallId: "retell_015",
    ingestedAt: ago(8 * DAY + 1 * HOUR),
  },
];
