/**
 * CDT code → readable procedure name.
 *
 * Ported VERBATIM from the legacy TC app (client/src/lib/odApi.ts). Open Dental
 * does not always return a description with a treatment-plan procedure — proctp
 * rows in particular often come back with an empty description — so a pulled plan
 * would otherwise show a bare code like "D2750" to the patient. This map is the
 * fallback that keeps the presentation readable.
 *
 * Not a clinical authority: OD's own description always wins when present.
 */
export const CODE_DESCRIPTIONS: Record<string, string> = {
  // Diagnostic
  D0120: "Periodic oral evaluation",
  D0140: "Limited oral evaluation",
  D0150: "Comprehensive oral evaluation",
  D0210: "Full mouth radiographic series",
  D0220: "Periapical radiograph — first image",
  D0230: "Periapical radiograph — additional image",
  D0240: "Occlusal radiographic image",
  D0270: "Bitewing — single image",
  D0272: "Bitewings — two images",
  D0274: "Bitewings — four images",
  D0330: "Panoramic radiographic image",
  D0340: "2D cephalometric radiographic image",
  D0350: "Oral/facial photographic images",
  D0364: "Cone beam CT — limited area",
  D0365: "Cone beam CT — full skull",
  // Preventive
  D1110: "Prophylaxis — adult",
  D1120: "Prophylaxis — child",
  D1206: "Topical fluoride varnish",
  D1208: "Topical fluoride — excluding varnish",
  D1310: "Nutritional counseling",
  D1351: "Sealant — per tooth",
  D1352: "Preventive resin restoration",
  // Restorative
  D2140: "Amalgam restoration — 1 surface, primary",
  D2150: "Amalgam restoration — 2 surfaces, primary",
  D2160: "Amalgam restoration — 3 surfaces, primary",
  D2161: "Amalgam restoration — 4+ surfaces, primary",
  D2330: "Resin composite — 1 surface, anterior",
  D2331: "Resin composite — 2 surfaces, anterior",
  D2332: "Resin composite — 3 surfaces, anterior",
  D2335: "Resin composite — 4+ surfaces, anterior",
  D2390: "Resin composite crown — anterior",
  D2391: "Resin composite — 1 surface, posterior",
  D2392: "Resin composite — 2 surfaces, posterior",
  D2393: "Resin composite — 3 surfaces, posterior",
  D2394: "Resin composite — 4+ surfaces, posterior",
  D2710: "Crown — resin (indirect)",
  D2712: "Crown — ¾ resin-based composite",
  D2720: "Crown — resin with high noble metal",
  D2721: "Crown — resin with predominantly base metal",
  D2722: "Crown — resin with noble metal",
  D2740: "Crown — porcelain/ceramic",
  D2750: "Crown — porcelain fused to high noble metal",
  D2751: "Crown — porcelain fused to predominantly base metal",
  D2752: "Crown — porcelain fused to noble metal",
  D2780: "Crown — 3/4 cast high noble metal",
  D2790: "Crown — full cast high noble metal",
  D2910: "Re-cement or re-bond inlay, onlay, veneer or partial coverage restoration",
  D2920: "Re-cement or re-bond crown",
  D2930: "Prefabricated stainless steel crown — primary tooth",
  D2931: "Prefabricated stainless steel crown — permanent tooth",
  D2950: "Core buildup, including any pins when required",
  D2951: "Pin retention, per tooth",
  D2960: "Labial veneer — resin laminate, chairside",
  D2961: "Labial veneer — resin laminate, laboratory",
  D2962: "Labial veneer — porcelain laminate, laboratory",
  D2971: "Additional procedures to construct new crown under existing partial denture framework",
  D2980: "Crown repair",
  // Endodontics
  D3110: "Pulp cap — direct",
  D3120: "Pulp cap — indirect",
  D3220: "Therapeutic pulpotomy",
  D3310: "Endodontic therapy — anterior tooth",
  D3320: "Endodontic therapy — premolar tooth",
  D3330: "Endodontic therapy — molar tooth",
  D3346: "Retreatment of previous root canal — anterior",
  D3347: "Retreatment of previous root canal — premolar",
  D3348: "Retreatment of previous root canal — molar",
  D3410: "Apicoectomy — anterior",
  D3421: "Apicoectomy — premolar, first root",
  D3425: "Apicoectomy — molar, first root",
  // Periodontics
  D4210: "Gingivectomy or gingivoplasty — 4+ teeth per quadrant",
  D4211: "Gingivectomy or gingivoplasty — 1–3 teeth per quadrant",
  D4240: "Gingival flap procedure — 4+ teeth per quadrant",
  D4241: "Gingival flap procedure — 1–3 teeth per quadrant",
  D4249: "Clinical crown lengthening — hard tissue",
  D4260: "Osseous surgery — 4+ teeth per quadrant",
  D4261: "Osseous surgery — 1–3 teeth per quadrant",
  D4341: "Periodontal scaling and root planing — 4+ teeth per quadrant",
  D4342: "Periodontal scaling and root planing — 1–3 teeth per quadrant",
  D4355: "Full mouth debridement",
  D4381: "Localized delivery of antimicrobial agents",
  D4910: "Periodontal maintenance",
  // Prosthodontics — removable
  D5110: "Complete denture — maxillary",
  D5120: "Complete denture — mandibular",
  D5130: "Immediate complete denture — maxillary",
  D5140: "Immediate complete denture — mandibular",
  D5211: "Maxillary partial denture — resin base",
  D5212: "Mandibular partial denture — resin base",
  D5213: "Maxillary partial denture — cast metal framework",
  D5214: "Mandibular partial denture — cast metal framework",
  D5410: "Adjust complete denture — maxillary",
  D5411: "Adjust complete denture — mandibular",
  D5421: "Adjust partial denture — maxillary",
  D5422: "Adjust partial denture — mandibular",
  D5511: "Repair broken complete denture base — maxillary",
  D5512: "Repair broken complete denture base — mandibular",
  D5621: "Repair cast framework — maxillary",
  D5622: "Repair cast framework — mandibular",
  D5710: "Rebase complete maxillary denture",
  D5711: "Rebase complete mandibular denture",
  D5720: "Rebase maxillary partial denture",
  D5721: "Rebase mandibular partial denture",
  D5730: "Reline complete maxillary denture (chairside)",
  D5731: "Reline complete mandibular denture (chairside)",
  // Implants
  D6010: "Surgical placement of implant body",
  D6013: "Surgical placement of mini implant",
  D6040: "Surgical placement — eposteal implant body",
  D6050: "Surgical placement — transosteal implant body",
  D6051: "Interim implant crown",
  D6052: "Semi-precision attachment abutment",
  D6055: "Connecting bar — implant-supported or implant/abutment supported",
  D6056: "Prefabricated abutment",
  D6057: "Custom fabricated abutment",
  D6058: "Implant supported crown — porcelain fused to high noble metal",
  D6059: "Implant supported crown — porcelain fused to predominantly base metal",
  D6060: "Implant supported crown — porcelain fused to noble metal",
  D6061: "Implant supported crown — predominantly base metal",
  D6062: "Implant supported crown — noble metal",
  D6065: "Implant supported crown — porcelain/ceramic",
  D6066: "Implant supported crown — cast high noble metal",
  D6067: "Implant supported crown — metal",
  D6068: "Implant supported retainer for porcelain/ceramic FPD",
  D6069: "Implant supported retainer for porcelain fused to metal FPD",
  D6070: "Implant supported retainer for cast metal FPD — high noble",
  D6071: "Implant supported retainer for cast metal FPD — predominantly base",
  D6072: "Implant supported retainer for cast metal FPD — noble",
  D6075: "Implant supported retainer for ceramic FPD",
  D6080: "Implant maintenance procedures, when prosthesis removed and reinserted",
  D6081: "Scaling and debridement in the presence of inflammation around implant",
  D6082: "Implant supported crown — porcelain fused to predominantly base metal",
  D6083: "Implant supported crown — porcelain fused to noble metal",
  D6084: "Implant supported crown — cast high noble metal",
  D6085: "Interim implant prosthesis",
  D6086: "Implant supported crown — predominantly base metal",
  D6087: "Implant supported crown — noble metal",
  D6088: "Implant supported crown — alternative materials",
  D6089: "Implant supported FPD pontic — ceramic (other than high noble)",
  D6090: "Implant supported FPD pontic — high noble metal",
  D6091: "Implant supported FPD pontic — predominantly base metal",
  D6092: "Re-cement or re-bond implant/abutment supported crown",
  D6093: "Re-cement or re-bond implant/abutment supported FPD",
  D6094: "Abutment supported crown (cast metal)",
  D6095: "Abutment supported retainer for metal FPD (cast predominantly base metal)",
  D6096: "Remove broken implant retaining screw",
  D6097: "Abutment supported crown, porcelain fused to metal",
  D6098: "Implant supported retainer — porcelain/ceramic",
  D6099: "Implant supported retainer for FPD — resin with high noble metal",
  D6100: "Implant removal, by report",
  D6101: "Debridement of a peri-implant defect",
  D6102: "Debridement and osseous contouring of a peri-implant defect",
  D6103: "Bone graft for repair of peri-implant defect",
  D6104: "Bone graft with major membrane",
  D6110: "Implant supported complete denture (maxillary)",
  D6111: "Implant supported complete denture (mandibular)",
  D6112: "Implant supported partial denture (maxillary)",
  D6113: "Implant supported partial denture (mandibular)",
  D6114: "Implant supported removable denture (maxillary)",
  D6115: "Implant supported removable denture (mandibular)",
  D6116: "Implant supported removable denture — laboratory reline (maxillary)",
  D6117: "Implant supported removable denture — laboratory reline (mandibular)",
  D6118: "Implant supported removable denture — chairside reline (maxillary)",
  D6119: "Implant supported removable denture — chairside reline (mandibular)",
  // Oral surgery
  D7111: "Extraction — coronal remnants, deciduous tooth",
  D7140: "Extraction — erupted tooth or exposed root",
  D7210: "Extraction — erupted tooth requiring removal of bone and/or sectioning",
  D7220: "Removal of impacted tooth — soft tissue",
  D7230: "Removal of impacted tooth — partially bony",
  D7240: "Removal of impacted tooth — completely bony",
  D7241: "Removal of impacted tooth — completely bony, with unusual surgical complications",
  D7250: "Removal of residual tooth roots",
  D7260: "Oroantral fistula closure",
  D7270: "Tooth reimplantation and/or stabilization of accidentally avulsed",
  D7280: "Exposure of an unerupted tooth",
  D7285: "Incisional biopsy of oral tissue — hard",
  D7286: "Incisional biopsy of oral tissue — soft",
  D7288: "Brush biopsy — transepithelial sample collection",
  D7291: "Transseptal fiberotomy/supra crestal fiberotomy",
  D7310: "Alveoloplasty with extractions — 4 or more teeth per quadrant",
  D7311: "Alveoloplasty with extractions — 1–3 teeth per quadrant",
  D7320: "Alveoloplasty without extractions — 4 or more teeth per quadrant",
  D7321: "Alveoloplasty without extractions — 1–3 teeth per quadrant",
  D7340: "Vestibuloplasty — ridge extension (secondary epithelialization)",
  D7350: "Vestibuloplasty — ridge extension (including soft tissue grafts)",
  D7410: "Excision of benign lesion — up to 1.25 cm",
  D7411: "Excision of benign lesion — greater than 1.25 cm",
  D7412: "Excision of benign lesion complicated",
  D7413: "Excision of malignant lesion — up to 1.25 cm",
  D7414: "Excision of malignant lesion — greater than 1.25 cm",
  D7415: "Excision of malignant lesion complicated",
  D7441: "Excision of malignant tumor — up to 1.25 cm",
  D7450: "Removal of benign odontogenic cyst or tumor — up to 1.25 cm",
  D7451: "Removal of benign odontogenic cyst or tumor — greater than 1.25 cm",
  D7460: "Removal of benign nonodontogenic cyst or tumor — up to 1.25 cm",
  D7461: "Removal of benign nonodontogenic cyst or tumor — greater than 1.25 cm",
  D7471: "Removal of lateral exostosis (maxilla or mandible)",
  D7472: "Removal of torus palatinus",
  D7473: "Removal of torus mandibularis",
  D7485: "Reduction of osseous tuberosity",
  D7490: "Surgical repositioning of teeth",
  D7510: "Incision and drainage of abscess — intraoral",
  D7511: "Incision and drainage of abscess — intraoral complicated",
  D7520: "Incision and drainage of abscess — extraoral",
  D7521: "Incision and drainage of abscess — extraoral complicated",
  D7530: "Removal of foreign body from mucosa, skin, or subcutaneous alveolar tissue",
  D7540: "Removal of reaction producing foreign bodies",
  D7550: "Partial ostectomy/sequestrectomy for removal of non-vital bone",
  D7560: "Maxillary sinusotomy for removal of tooth fragment or foreign body",
  D7610: "Maxilla — open reduction (teeth immobilized, if present)",
  D7630: "Mandible — open reduction (teeth immobilized, if present)",
  D7640: "Mandible — closed reduction (teeth immobilized, if present)",
  D7650: "Malar and/or zygomatic arch — open reduction",
  D7660: "Malar and/or zygomatic arch — closed reduction",
  D7670: "Alveolus — closed reduction stabilization of teeth",
  D7680: "Facial bones — complicated reduction with fixation and multiple surgical approaches",
  D7710: "Maxilla — open reduction",
  D7720: "Maxilla — closed reduction",
  D7730: "Mandible — open reduction",
  D7740: "Mandible — closed reduction",
  D7750: "Malar and/or zygomatic arch — open reduction",
  D7760: "Malar and/or zygomatic arch — closed reduction",
  D7770: "Alveolus — open reduction stabilization of teeth",
  D7771: "Alveolus, closed reduction stabilization of teeth",
  D7780: "Facial bones — complicated reduction with fixation and multiple surgical approaches",
  D7810: "Open reduction of dislocation",
  D7820: "Closed reduction of dislocation",
  D7830: "Manipulation under anesthesia",
  D7840: "Condylectomy",
  D7850: "Surgical discectomy, with or without implant",
  D7852: "Disc repair",
  D7854: "Synovectomy",
  D7856: "Myotomy",
  D7858: "Joint reconstruction",
  D7860: "Arthroscopy",
  D7865: "Arthroplasty",
  D7870: "Arthrocentesis",
  D7871: "Non-arthroscopic lysis and lavage",
  D7872: "Arthroscopy — diagnosis, with or without biopsy",
  D7873: "Arthroscopy — surgical, lavage and lysis of adhesions",
  D7874: "Arthroscopy — surgical, disc repositioning and stabilization",
  D7875: "Arthroscopy — surgical, synovectomy",
  D7876: "Arthroscopy — surgical, discectomy",
  D7877: "Arthroscopy — surgical, debridement",
  D7880: "Occlusal orthotic device, by report",
  D7881: "Occlusal orthotic device adjustment",
  D7899: "Unspecified TMD therapy, by report",
  D7910: "Suture of recent small wounds up to 5 cm",
  D7911: "Complicated suture — up to 5 cm",
  D7912: "Complicated suture — greater than 5 cm",
  D7920: "Skin graft (identify defect covered, location, size, and type of graft)",
  D7940: "Osteoplasty — for orthognathic deformities",
  D7941: "Osteotomy — mandibular rami",
  D7943: "Osteotomy — mandibular rami with bone graft",
  D7944: "Osteotomy — segmented or subapical — mandible",
  D7945: "Osteotomy — body of mandible",
  D7946: "LeFort I (maxilla — total)",
  D7947: "LeFort I (maxilla — segmented)",
  D7948: "LeFort II or LeFort III (osteoplasty of facial bones for midface hypoplasia)",
  D7949: "LeFort II or LeFort III with bone graft",
  D7950: "Osseous, osteoperiosteal, or cartilage graft of the mandible or maxilla",
  D7951: "Sinus augmentation with bone or bone substitutes via a lateral open approach",
  D7952: "Sinus augmentation via a vertical/crestal approach",
  D7953: "Bone replacement graft for ridge preservation — per site",
  D7955: "Repair of maxillofacial soft and/or hard tissue defect",
  D7960: "Frenulectomy — separate procedure",
  D7963: "Frenuloplasty",
  D7971: "Excision of pericoronal gingiva",
  D7972: "Surgical reduction of fibrous tuberosity",
  D7979: "Unspecified oral surgery procedure, by report",
  D7980: "Sialolithotomy",
  D7981: "Excision of salivary gland, by report",
  D7982: "Sialodochoplasty",
  D7983: "Closure of salivary fistula",
  D7990: "Emergency tracheotomy",
  D7991: "Coronoidectomy",
  D7993: "Surgical placement of craniofacial implant — extraoral",
  D7994: "Surgical placement: zygomatic implant",
  D7995: "Synthetic graft — mandible or facial bones, by report",
  D7996: "Implant-supported palatal expansion appliance",
  D7997: "Appliance removal (not including removal of implant supported devices)",
  D7999: "Unspecified oral surgery procedure, by report",
  // Orthodontics
  D8010: "Limited orthodontic treatment of the primary dentition",
  D8020: "Limited orthodontic treatment of the transitional dentition",
  D8030: "Limited orthodontic treatment of the adolescent dentition",
  D8040: "Limited orthodontic treatment of the adult dentition",
  D8050: "Interceptive orthodontic treatment of the primary dentition",
  D8060: "Interceptive orthodontic treatment of the transitional dentition",
  D8070: "Comprehensive orthodontic treatment of the transitional dentition",
  D8080: "Comprehensive orthodontic treatment of the adolescent dentition",
  D8090: "Comprehensive orthodontic treatment of the adult dentition",
  D8660: "Pre-orthodontic treatment examination to monitor growth and development",
  D8670: "Periodic orthodontic treatment visit (as part of contract)",
  D8680: "Orthodontic retention",
  D8681: "Removable orthodontic retainer adjustment",
  D8695: "Removal of fixed orthodontic appliances for reason other than completion of treatment",
  D8696: "Repair of orthodontic appliance",
  D8697: "Re-cement or re-bond fixed retainer",
  D8698: "Re-cement or re-bond fixed retainer — mandibular",
  D8699: "Re-cement or re-bond fixed retainer — maxillary",
  D8701: "Repair of fixed retainer — includes reattachment",
  D8702: "Replacement of lost or broken retainer",
  D8703: "Replacement of lost or broken retainer — mandibular",
  D8999: "Unspecified orthodontic procedure, by report",
  // Adjunctive
  D9110: "Palliative (emergency) treatment of dental pain — minor procedure",
  D9120: "Fixed partial denture sectioning",
  D9210: "Local anesthesia not in conjunction with operative or surgical procedures",
  D9211: "Regional block anesthesia",
  D9212: "Trigeminal division block anesthesia",
  D9215: "Local anesthesia in conjunction with operative or surgical procedures",
  D9219: "Evaluation for moderate sedation",
  D9222: "Deep sedation/general anesthesia — first 15 minutes",
  D9223: "Deep sedation/general anesthesia — each subsequent 15 minutes",
  D9230: "Inhalation of nitrous oxide / anxiolysis, analgesia",
  D9239: "Intravenous moderate (conscious) sedation/analgesia",
  D9241: "Intravenous moderate (conscious) sedation/analgesia — first 15 minutes",
  D9242: "Intravenous moderate (conscious) sedation/analgesia — each subsequent 15 minutes",
  D9248: "Non-intravenous conscious sedation",
  D9310: "Consultation — diagnostic service provided by dentist or physician other than requesting dentist or physician",
  D9311: "Consultation with a medical health care professional",
  D9410: "House/extended care facility call",
  D9420: "Hospital or ambulatory surgical center call",
  D9430: "Office visit for observation (during regularly scheduled hours) — no other services performed",
  D9440: "Office visit — after regularly scheduled hours",
  D9450: "Case presentation, detailed and extensive treatment planning",
  D9610: "Injection of therapeutic drug",
  D9612: "Topical application of antimicrobial drug",
  D9613: "Infiltration of sustained release therapeutic drug — single site",
  D9620: "Injection of botulinum toxin",
  D9630: "Drugs or medicaments dispensed in the office for home use",
  D9910: "Application of desensitizing medicament",
  D9911: "Application of desensitizing resin for cervical and/or root surface",
  D9920: "Behavior management, by report",
  D9930: "Treatment of complications (post-surgical) — unusual circumstances, by report",
  D9932: "Cleaning and inspection of removable complete denture, maxillary",
  D9933: "Cleaning and inspection of removable complete denture, mandibular",
  D9934: "Cleaning and inspection of removable partial denture, maxillary",
  D9935: "Cleaning and inspection of removable partial denture, mandibular",
  D9940: "Occlusal guard — hard appliance, full arch",
  D9941: "Fabrication of athletic mouthguard",
  D9942: "Occlusal guard — soft appliance, full arch",
  D9943: "Occlusal guard — hard appliance, partial arch",
  D9944: "Occlusal guard — soft appliance, partial arch",
  D9945: "Occlusal guard adjustment",
  D9946: "Occlusal guard — hard appliance, full arch — delivery and follow-up",
  D9950: "Occlusion analysis — mounted case",
  D9951: "Occlusal adjustment — limited",
  D9952: "Occlusal adjustment — complete",
  D9961: "Duplicate/copy patient records",
  D9970: "Enamel microabrasion",
  D9971: "Odontoplasty, 1–2 teeth; includes removal of enamel projections",
  D9972: "External bleaching — per arch; performed in office",
  D9973: "External bleaching — per tooth",
  D9974: "Internal bleaching — per tooth",
  D9975: "External bleaching for home application, per arch; fabrication and custom tray",
  D9985: "Sales tax",
  D9986: "Missed appointment",
  D9987: "Cancelled appointment",
  D9990: "Limited oral evaluation — problem focused",
  D9991: "Dental case management — addressing appointment compliance barriers",
  D9992: "Dental case management — care coordination",
  D9993: "Dental case management — motivational interviewing",
  D9994: "Dental case management — patient education to improve oral health literacy",
  D9995: "Teledentistry — synchronous; real-time encounter",
  D9996: "Teledentistry — asynchronous; information stored and forwarded to dentist",
  D9997: "Dental case management — patients with special health care needs",
  D9999: "Unspecified adjunctive procedure, by report",
};

/**
 * Readable name for a procedure: Open Dental's own description first, this map
 * second, the raw code last. Never returns an empty string.
 */
export function describeCode(procCode: string, fallback?: string): string {
  const code = (procCode || "").trim().toUpperCase();
  if (fallback && fallback.trim()) return fallback.trim();
  return CODE_DESCRIPTIONS[code] || code || "Procedure";
}
